name: Build Windows Fork

on:
  push:
    branches:
      - '**'
    paths:
      - 'deps/**'
      - 'deps_src/**'
      - 'src/**'
      - '**/CMakeLists.txt'
      - 'version.inc'
      - 'resources/**'
      - 'scripts/**'
      - '.github/workflows/build_*.yml'
      - '.github/actions/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'deps/**'
      - 'deps_src/**'
      - 'src/**'
      - '**/CMakeLists.txt'
      - 'version.inc'
      - 'resources/**'
      - 'scripts/**'
      - '.github/workflows/build_*.yml'
      - '.github/actions/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_windows:
    uses: ./.github/workflows/build_check_cache.yml
    with:
      os: windows-latest
      build-deps-only: false
